title_primary: "ç³–çŒ«çš„å¤å¤©" # the bigger text
title_secondary: "ä½ é—®æˆ‘å…¨ä¸–ç•Œå“ªé‡Œæœ€ç¾ï¼Œç­”æ¡ˆæ˜¯ä½ èº«è¾¹" # the smaller text
keywords:

twitter: #sugar
rss: #atom.xml
weibo: 2668548383
instagram: #username
github: #sugar-cat

# Choose the comment service according to your need.
# Please do not use the two services at the same time.
livere: # [data-uid] on livere.com
disqus: # [short_name] on disqus.com
dove: # For fun ONLY. Set to true to 'disable' comments on your site.
valine: false
valine_appid: 'ivKXN7cYkw8io7c8QWxCV3Cg-gzGzoHsz'
valine_appkey: 'ScJx4OsdyFyPVhOWMkSMRVsg'

# Set true to show the page indicator.
showPageCount: true

# Set true to show catego.ry or tags behind post titles
showCategories: true
showTags: true

# Color schemeä½ æ˜¯æˆ‘äººä¸–é—´ğŸ’“æœ€å¥‘åˆæµªæ¼«çš„å› æœâœ¨
themeStyle: light # light/dark
